### PR TITLE
Perimeter Center West

### PR DESCRIPTION
**Pull request by KWescott-SandySprings**
Changing road ID #1213142623 functional class from 7 (Local) to 4 (Minor arterial).
### Description

0.36 mi, 45 mph, ADT 27,300 vpd.  Perimeter Center West is on the same alignment as Abernathy Road and connects SR 400 to the Perimeter business district.
### Justification

Regional significance, Multi-lane Divided Street, Continuity.  The City's adopted classification is Minor Arterial. This segment was identified as a Minor Arterial in the Georgia DOT 2010 Classification map. Abernathy Road to the west is classified Principal Arterial.  It is the City's understanding that Dunwoody is seeking Principal Arterial classification on the remaining (longer) segment between the city limits and Ashford Dunwoody Road.  This modification will require review and approval by the Sandy Springs City Council.
#### County

Fulton County

### CODE REVIEW

**Comment by davidhaynes** [comment]
Sandy Springs has submitted two requests (#692 and #494) to upgrade Abernathy Road / Perimeter Center West to principal arterial.  This would require upgrading another segment to the east of the DeKalb County line within Dunwoody, but no such request was submitted.  GDOT does not concur with the upgrade requests since the road primarily serves traffic with a local origin and/or destination.  The facility is also not located on the regional thoroughfares network, so ARC would concur with GDOT that remaining a minor arterial is the appropriate regional designation.

**Comment by KWescott-SandySprings** [comment]
It was my understanding that Dunwoody would also request Principal Arterial status for Perimeter Center West.  I did want to let you know that the short segment of Perimeter Center West between Abernathy Road and the city limits of Dunwoody was in the GitHub database as unclassified.  Will this error be corrected to show that Perimeter Center West is classified as a minor arterial within Sandy Springs?  

If this is the right time to ask, I would request that ARC consider adding Perimeter Center West to the Regional Thoroughfares Network.  The alignment of Johnson Ferry Road from Cobb to Abernathy Road is a classified as a Principal Arterial to SR 400.  Regional traffic travelling along this corridor does not necessarily exit/enter at SR 400, they continue east/south on Perimeter Center West to major office and commercial developments in Perimeter.  Perimeter Center West is one of only two major east-west surface street connecting SR 400, Peachtree Dunwoody Road, and Ashford Dunwoody Road.  There are only a few connected streets w/in Perimeter that provide regional access to the Perimeter office market east of SR 400 and north of I-285:  Peachtree Dunwoody Road, Hammond Drive, Abernathy Road, and Perimeter Center West in Sandy Springs and Ashford Dunwoody Road and Perimeter Center Parkway in Dunwoody.

I would encourage ARC to examine the relative utilization, connectivity, and access of the arterial street network within Perimeter for their inclusion in the Regional Thoroughfares Network.  Most of the arterial network within the Sandy Springs portion of the Perimeter carry upwards of mid-20,000 to 50,000 vehicles per day.  I am not sure how regional traffic could possibly access the Perimeter regional activity center destinations without these surface streets.

**Comment by MWillisARC** [comment]
The request from Dunwoody to upgrade Perimeter Center West is Issue #201 and is included in GitHub.

**Comment by MWillisARC** [comment]
#692 marked as **On Hold**  by @MWillisARC at 08:47 am on 7/31/14

**Pull request closed without merging**
