### PR TITLE
GA Hwy 92

### PR DESCRIPTION
**Pull request by MWillisARC**
Changing road ID #0971007000 functional class from 4 (Minor arterial) to 3 (Principal arterial).
### Description

Randy Hulsey request 6/25/2014.  Will follow-up in July.
### Justification

Randy Hulsey request 6/25/2014.  Will follow-up in July.
#### From

Fairburn/Campbellton
#### To

Fulton/City of Campbellton
#### County

Douglas County

### CODE REVIEW

**Comment by MWillisARC** [comment]
Both sides of the branch are requested to be Principal Arterial.

**Comment by MWillisARC** [comment]
#880 marked as **Advancing**  by @MWillisARC at 13:32 pm on 7/16/14

**Comment by davidhaynes** [comment]
Numerous requests have been submitted by Douglas County, Paulding County and ARC (#1009, #880, #879, #881, #328, #1008, #331 and #1012) to create a continuous principal arterial designation along SR 92 between US 29 in Fairburn and US 41 in Cobb County.  Geometric conditions vary along the corridor and some sections in Douglas County are on the verge of being realigned and widened.  ARC believes that the corridor is already serving a critical north/south mobility function along the entire western side of the region and this role will only continue to grow as other major sections of the corridor are widened.  GDOT has expressed reluctance at upgrading some sections until widening projects are complete, but this would result in a piecemeal functional classification along the corridor since widenings are programmed at different times over the next 10+ years.  ARC recommends upgrading the entire corridor in the near future, but concurs that this redesignation could wait until after the realigned section around Douglasville has been completed.  Additional discussion with GDOT and the local governments should occur before any final recommendations are made anywhere along the corridor and advanced through the ARC committee approval process.

**Comment by MWillisARC** [comment]
Changes 2014-038, 2014-039A, 2014-043, 2014-044 and 2014-048 are contiguous along a single corridor; changes 2014-039A and 2014-039B were submitted jointly under one GitHub request, but are split apart in this table for clarity

**Pull request closed without merging**
